In [ ]:
import pandas as pd 
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report
import re 
import joblib
import string

In [7]:
fake = pd.read_csv('Fake.csv')
true = pd.read_csv('True.csv')

In [10]:
fake.head()

,title,text,subject,date,class
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017",1
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017",1
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017",1
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017",1
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017",1

In [8]:
true.head()

,title,text,subject,date
0,"As U.S. budget fight looms, Republicans flip t...",WASHINGTON (Reuters) - The head of a conservat...,politicsNews,"December 31, 2017"
1,U.S. military to accept transgender recruits o...,WASHINGTON (Reuters) - Transgender people will...,politicsNews,"December 29, 2017"
2,Senior U.S. Republican senator: 'Let Mr. Muell...,WASHINGTON (Reuters) - The special counsel inv...,politicsNews,"December 31, 2017"
3,FBI Russia probe helped by Australian diplomat...,WASHINGTON (Reuters) - Trump campaign adviser ...,politicsNews,"December 30, 2017"
4,Trump wants Postal Service to charge 'much mor...,SEATTLE/WASHINGTON (Reuters) - President Donal...,politicsNews,"December 29, 2017"

In [37]:
fake['class']=0
true['class']=1

In [11]:
data = pd.concat([fake,true], axis = 0)

In [12]:
data.sample(10)

,title,text,subject,date,class
14973,UK PM May wants to agree outline Brexit transi...,LONDON (Reuters) - British Prime Minister Ther...,worldnews,"November 13, 2017",NaN
15177,HERE’S THE LIST Of Heartless Senators Who Vote...,Godless heartless and without conscience .Sena...,politics,"Sep 23, 2015",1.0
14552,Two killed as Kenyan police disperse oppositio...,NAIROBI (Reuters) - Two people were shot dead ...,worldnews,"November 17, 2017",NaN
22300,Boiler Room #90 – Downtown Brown and The Loss ...,Tune in to the Alternate Current Radio Network...,US_News,"December 29, 2016",1.0
14694,Cambodia's opposition braces for Supreme Court...,PHNOM PENH (Reuters) - Cambodia s Supreme Cour...,worldnews,"November 16, 2017",NaN
1361,Blackwater founder Prince weighing U.S. Senate...,"WASHINGTON (Reuters) - Erik Prince, who founde...",politicsNews,"October 8, 2017",NaN
938,WATCH: Republican Who Voted To Impeach Clinto...,The Republican effort to impeach former Presid...,News,"July 4, 2017",1.0
8370,Obama expands Hawaii marine reserve in final p...,WASHINGTON (Reuters) - U.S. President Barack O...,politicsNews,"August 26, 2016",NaN
15024,WHY RUSH LIMBAUGH Thinks GOP Voters Shouldn’t ...,He s always been in our top three. A rock soli...,politics,"Oct 26, 2015",1.0
2581,The Look On The Japanese Leader’s Face After ...,Alleged president Donald Trump met with Japane...,News,"February 10, 2017",1.0

In [13]:
data = data.drop(["title","subject","date"], axis = 1)

In [14]:
data.reset_index(inplace=True)

In [15]:
data.drop(['index'], axis = 1,inplace=True)

In [16]:
data.sample(5)

                                                    text  class
6980   Arizona Speaker of the House David Gowan (R) e...    1.0
7944   One of the most beloved public figures in the ...    1.0
11076  The poll below is why people shouldn t trust p...    1.0
97     After Hollywood producer Harvey Weinstein was ...    1.0
21814  Wouldn t it be great if our first  Black  Pres...    1.0

In [ ]:
def clean_text(text):
    text = re.sub(r'\[.*?\]', "", text)                     # remove [..]
    text = re.sub(r'http\S+|www\.\S+', "", text)            # remove links
    text = re.sub(r'<.*?>+', "", text)                      # remove HTML tags
    text = re.sub(r'[%s]' % re.escape("""!"#$%&'()*+,-./:;<=>?@[]^_`{|}~"""), "", text)  # remove punctuations
    text = re.sub(r'\n', "", text)                          # remove newlines
    text = re.sub(r'\w*\d\w*', "", text)                    # remove words containing numbers
    return text

In [27]:
data["text"] = data["text"].apply(clean_text)

In [61]:
x=data["text"]
y=data["class"]

xtrain, xtest, ytrain, ytest = train_test_split(x,y,test_size=0.25,random_state=42)

In [55]:
vectorizer = TfidfVectorizer()
xv_train = vectorizer.fit_transform(xtrain)
xv_test = vectorizer.transform(xtest)

In [ ]:
lr = LogisticRegression()
lr.fit(xv_train,ytrain)

In [ ]:
prediction = lr.predict(xv_test)
lr.score(xv_test,ytest)

In [ ]:
print(classification_report(ytest,prediction))

In [48]:
joblib.dump(vectorizer,"vectorizer.jb")
joblib.dump(lr,"lr_model.jb")

['lr_model.jb']